### ISSUE TITLE
User friendly navigation and responsive design

### ISSUE THREAD

**Issue by naomihunt25** [naomihunt25/ceioty-media#1]
**User Story**
As a first-time visitor, I want to quickly understand what Ceioty Media does and explore examples of their work through easy navigation and a user-friendly design. Their website suit include a responsive layout for my device so I can navigate their website with ease. 

**Acceptance Criteria**
- [ ] The website is fully responsive and loads promptly across a variety of devices and screen sizes.
- [ ] Site layout and navigation is easy to follow.
- [ ] 

**Tasks**
- [ ] Arrange the site layout and navigation so that it is intuitive, allowing the user to easily access each page.
- [ ] Apply responsive design principles using tools such as Bootstrap to ensure the website is easily accessible for different screen sizes.
