### ISSUE TITLE
High quality portfolio

### ISSUE THREAD

**Issue by naomihunt25** [naomihunt25/ceioty-media#2]
**User Story**
As a Casual Gamer, I want to see high-quality images and engaging descriptions of the café's ambience and some of the available games, so I can decide if it's the right place for me to relax and have fun.

**Acceptance Criteria**
- [ ] Users can view high quality images and smoothly play videos on all devices.
- [ ] Media loads within 2–3 seconds and does not impact overall website performance.

**Tasks**
- [ ] Curate a selection of high quality images and videos.
- [ ] Optimise media files for web use without compromising quality by using WebP format.
