### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by naomihunt25** [naomihunt25/ceioty-media#3]
**User Story**
As a Prospective Customer, I need to find essential information such as contact details and social media accounts, so I can easily get in touch with Ceioty Media.

**Acceptance Criteria**
- [ ] The website contains a dedicated section for contact details and social links.
- [ ] The section is clearly visible and accessible from all parts of the website.

**Tasks**
- [ ] Design and place a section for details and social links.
- [ ] Ensure the contact section is clearly visible and accessible from all parts of the website.
