### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by naomihunt25** [naomihunt25/ceioty-media#4]
**User Story**
As a Customer, I want to be able to contact Ceioty Media to discuss project ideas, pricing and for them to answer any additional queries I have. 

**Acceptance Criteria**
- [ ] The contact form is easy to find and use, functional and submits data securely without errors.
- [ ] The form includes all necessary fields to gather event details: Name, Email, Phone Number and Message. 
- [ ] All fields on the form must be completed before the user can submit the form.
- [ ] Users receive a confirmation message after form submission.

**Tasks**
- [ ] Implement a contact form on the website.
- [ ] Implement HTML validation on the form to fit the requirements above.
- [ ] Create a success page to direct users to after submitting the form.
