### ISSUE TITLE
High quality portfolio

### ISSUE THREAD

**Issue by naomihunt25** [naomihunt25/ceioty-media#5]
**User Story**
As a prospective customer, I want to see high-quality images, so I can decide if I would like to work with Ceioty Media. 

**Acceptance Criteria**
- [ ] Users can view high quality images and smoothly play videos on all devices.
- [ ] Media loads within 2–3 seconds and does not impact overall website performance.

**Tasks**
- [ ] Curate a selection of high quality images and videos.
- [ ] Optimise media files for web use without compromising quality by using WebP format.
