### ISSUE TITLE
Newsletter sign up form

### ISSUE THREAD

**Issue by naomihunt25** [naomihunt25/ceioty-media#5]
**User Story**
As a repeat visitor and previous customer, I want to sign up for newsletters and updates, so I can stay informed about special offers, new portfolio work and their latest news.

**Acceptance Criteria**
- [ ] The website contains a sign up form for the Ceioty Media newsletter.
- [ ] The sign up form is placed on every page, so it can be easily accessed and highly visible.

**Tasks**
- [ ] Integrate the newsletter sign-up form into the website footer.
